# Generated by Django 4.2.2 on 2023-06-06 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 6, 17, 17, 48, 863455)),
        ),
    ]
