# Generated by Django 4.2.2 on 2023-10-24 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_alter_cart_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 15, 45, 23, 825353)),
        ),
    ]
