# Generated by Django 4.2.2 on 2023-11-06 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myorders_approved_date_myorders_approved_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='utr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 6, 15, 55, 6, 383918)),
        ),
    ]
