# Generated by Django 4.2.2 on 2023-11-06 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myorders_utr_id_alter_cart_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='reject_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='reject_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 6, 15, 57, 1, 407029)),
        ),
    ]
