# Generated by Django 4.2.7 on 2026-01-09 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myorders_reject_date_myorders_reject_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 9, 12, 34, 10, 16069)),
        ),
    ]
