# Generated by Django 4.2.7 on 2026-01-09 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_reviews_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 9, 12, 34, 10, 14425)),
        ),
    ]
