# Generated by Django 4.2.2 on 2023-06-06 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelManufacturing',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.IntegerField()),
                ('interested_in', models.CharField(choices=[('Skin-Care', 'Skincare'), ('Hair-Care', 'Haircare'), ('Eye-Care', 'Eyecare'), ('cleanser', 'Cleanser'), ('professional-care', 'Professional Care'), ('Sun-Care', 'Suncare')], default='skincare', max_length=100)),
                ('types_of_products', models.CharField(choices=[('natural', 'Natural'), ('organic', 'Organic'), ('chemical-free', 'Chemical Free'), ('vegan-friendly', 'Vegan Friendly'), ('paraben-free', 'Paraben Free')], default='Natural', max_length=100)),
                ('planning_to_choose', models.CharField(choices=[('within-a-month', 'Within a month'), ('one-to-six-month', 'One to six months'), ('just-inquiring', 'Just inquiring')], default='within_a_month', max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
